CREATE TABLE IF NOT EXISTS users (
  user_id BIGSERIAL PRIMARY KEY,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  first_name VARCHAR(63) NOT NULL,
  last_name VARCHAR(63) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(511) NOT NULL UNIQUE,
  dob DATE NOT NULL,
  time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  token VARCHAR(255) PRIMARY KEY,
  jwt VARCHAR(2047) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_in INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS blocked_jwts (
  token VARCHAR(2047) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_in INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users (user_id)
);
